#############################################################################
# Makefile for building: release/ESerialPort
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  ESerialPort.pro
# Template: app
# Command: /data/app/qt5.13/bin/qmake -o Makefile ESerialPort.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../app/qt5.13/include -I../../../../app/qt5.13/include/QtWidgets -I../../../../app/qt5.13/include/QtGui -I../../../../app/qt5.13/include/QtSerialPort -I../../../../app/qt5.13/include/QtCore -Irelease -isystem /usr/include/libdrm -Iui -I../../../../app/qt5.13/mkspecs/linux-g++
QMAKE         = /data/app/qt5.13/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /data/app/qt5.13/bin/qmake -install qinstall
QINSTALL_PROGRAM = /data/app/qt5.13/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ESerialPort1.0.0
DISTDIR = /data/work/workspace/etool/ESerialPort/release/ESerialPort1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/data/app/qt5.13/lib
LIBS          = $(SUBLIBS) /data/app/qt5.13/lib/libQt5Widgets.so /data/app/qt5.13/lib/libQt5Gui.so /data/app/qt5.13/lib/libQt5SerialPort.so /data/app/qt5.13/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = release/

####### Files

SOURCES       = src/main.cpp \
		src/widget.cpp release/moc_widget.cpp
OBJECTS       = release/main.o \
		release/widget.o \
		release/moc_widget.o
DIST          = ../../../../app/qt5.13/mkspecs/features/spec_pre.prf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/unix.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/linux.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/sanitize.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/g++-base.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../app/qt5.13/mkspecs/qconfig.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3drender.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_charts.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_core.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_core_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_dbus.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_designer.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_gui.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_help.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_help_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_location.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_location_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_network.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_network_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_nfc.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_opengl.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_positioning.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qml.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quick.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_repparser.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_script.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_script_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_scxml.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_sensors.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_serialport.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_sql.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_svg.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_testlib.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_uitools.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webengine.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_websockets.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webview.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_widgets.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xml.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../app/qt5.13/mkspecs/features/qt_functions.prf \
		../../../../app/qt5.13/mkspecs/features/qt_config.prf \
		../../../../app/qt5.13/mkspecs/linux-g++/qmake.conf \
		../../../../app/qt5.13/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../app/qt5.13/mkspecs/features/exclusive_builds.prf \
		../../../../app/qt5.13/mkspecs/features/toolchain.prf \
		../../../../app/qt5.13/mkspecs/features/default_pre.prf \
		../../../../app/qt5.13/mkspecs/features/resolve_config.prf \
		../../../../app/qt5.13/mkspecs/features/default_post.prf \
		../../../../app/qt5.13/mkspecs/features/warn_on.prf \
		../../../../app/qt5.13/mkspecs/features/qt.prf \
		../../../../app/qt5.13/mkspecs/features/resources.prf \
		../../../../app/qt5.13/mkspecs/features/moc.prf \
		../../../../app/qt5.13/mkspecs/features/unix/opengl.prf \
		../../../../app/qt5.13/mkspecs/features/uic.prf \
		../../../../app/qt5.13/mkspecs/features/unix/thread.prf \
		../../../../app/qt5.13/mkspecs/features/qmake_use.prf \
		../../../../app/qt5.13/mkspecs/features/file_copies.prf \
		../../../../app/qt5.13/mkspecs/features/testcase_targets.prf \
		../../../../app/qt5.13/mkspecs/features/exceptions.prf \
		../../../../app/qt5.13/mkspecs/features/yacc.prf \
		../../../../app/qt5.13/mkspecs/features/lex.prf \
		ESerialPort.pro src/widget.h src/main.cpp \
		src/widget.cpp
QMAKE_TARGET  = ESerialPort
DESTDIR       = release/
TARGET        = release/ESerialPort


first: all
####### Build rules

release/ESerialPort: ui/ui_widget.h $(OBJECTS)  
	@test -d release/ || mkdir -p release/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ESerialPort.pro ../../../../app/qt5.13/mkspecs/linux-g++/qmake.conf ../../../../app/qt5.13/mkspecs/features/spec_pre.prf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/unix.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/linux.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/sanitize.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/g++-base.conf \
		../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../app/qt5.13/mkspecs/qconfig.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3drender.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_charts.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_core.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_core_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_dbus.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_designer.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_gui.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_help.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_help_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_location.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_location_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_network.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_network_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_nfc.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_opengl.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_positioning.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qml.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quick.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_repparser.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_script.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_script_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_scxml.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_sensors.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_serialport.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_sql.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_svg.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_testlib.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_uitools.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webengine.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_websockets.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webview.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_widgets.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xml.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../app/qt5.13/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../app/qt5.13/mkspecs/features/qt_functions.prf \
		../../../../app/qt5.13/mkspecs/features/qt_config.prf \
		../../../../app/qt5.13/mkspecs/linux-g++/qmake.conf \
		../../../../app/qt5.13/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../app/qt5.13/mkspecs/features/exclusive_builds.prf \
		../../../../app/qt5.13/mkspecs/features/toolchain.prf \
		../../../../app/qt5.13/mkspecs/features/default_pre.prf \
		../../../../app/qt5.13/mkspecs/features/resolve_config.prf \
		../../../../app/qt5.13/mkspecs/features/default_post.prf \
		../../../../app/qt5.13/mkspecs/features/warn_on.prf \
		../../../../app/qt5.13/mkspecs/features/qt.prf \
		../../../../app/qt5.13/mkspecs/features/resources.prf \
		../../../../app/qt5.13/mkspecs/features/moc.prf \
		../../../../app/qt5.13/mkspecs/features/unix/opengl.prf \
		../../../../app/qt5.13/mkspecs/features/uic.prf \
		../../../../app/qt5.13/mkspecs/features/unix/thread.prf \
		../../../../app/qt5.13/mkspecs/features/qmake_use.prf \
		../../../../app/qt5.13/mkspecs/features/file_copies.prf \
		../../../../app/qt5.13/mkspecs/features/testcase_targets.prf \
		../../../../app/qt5.13/mkspecs/features/exceptions.prf \
		../../../../app/qt5.13/mkspecs/features/yacc.prf \
		../../../../app/qt5.13/mkspecs/features/lex.prf \
		ESerialPort.pro
	$(QMAKE) -o Makefile ESerialPort.pro
../../../../app/qt5.13/mkspecs/features/spec_pre.prf:
../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/unix.conf:
../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/linux.conf:
../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/sanitize.conf:
../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/gcc-base.conf:
../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/g++-base.conf:
../../../../app/Qt5.13.0/5.13.0/gcc_64/mkspecs/common/g++-unix.conf:
../../../../app/qt5.13/mkspecs/qconfig.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3danimation.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dcore.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dextras.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dinput.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquick.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3drender.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_charts.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_charts_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_concurrent.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_core.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_core_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_dbus.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_designer.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_designer_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_gamepad.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_gui.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_gui_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_help.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_help_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_input_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_location.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_location_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_multimedia.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_network.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_network_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_networkauth.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_nfc.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_opengl.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_positioning.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_printsupport.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_purchasing.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_qml.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_qml_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_qmltest.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_quick.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_quick_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_repparser.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_script.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_script_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_scripttools.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_scxml.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_sensors.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_serialbus.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_serialport.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_sql.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_sql_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_svg.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_svg_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_testlib.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_uitools.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandclient.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webchannel.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webengine.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_websockets.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webview.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_webview_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_widgets.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_x11extras.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_xml.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_xml_private.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../app/qt5.13/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../app/qt5.13/mkspecs/features/qt_functions.prf:
../../../../app/qt5.13/mkspecs/features/qt_config.prf:
../../../../app/qt5.13/mkspecs/linux-g++/qmake.conf:
../../../../app/qt5.13/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../app/qt5.13/mkspecs/features/exclusive_builds.prf:
../../../../app/qt5.13/mkspecs/features/toolchain.prf:
../../../../app/qt5.13/mkspecs/features/default_pre.prf:
../../../../app/qt5.13/mkspecs/features/resolve_config.prf:
../../../../app/qt5.13/mkspecs/features/default_post.prf:
../../../../app/qt5.13/mkspecs/features/warn_on.prf:
../../../../app/qt5.13/mkspecs/features/qt.prf:
../../../../app/qt5.13/mkspecs/features/resources.prf:
../../../../app/qt5.13/mkspecs/features/moc.prf:
../../../../app/qt5.13/mkspecs/features/unix/opengl.prf:
../../../../app/qt5.13/mkspecs/features/uic.prf:
../../../../app/qt5.13/mkspecs/features/unix/thread.prf:
../../../../app/qt5.13/mkspecs/features/qmake_use.prf:
../../../../app/qt5.13/mkspecs/features/file_copies.prf:
../../../../app/qt5.13/mkspecs/features/testcase_targets.prf:
../../../../app/qt5.13/mkspecs/features/exceptions.prf:
../../../../app/qt5.13/mkspecs/features/yacc.prf:
../../../../app/qt5.13/mkspecs/features/lex.prf:
ESerialPort.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ESerialPort.pro

qmake_all: FORCE


all: Makefile release/ESerialPort

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../app/qt5.13/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/widget.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: release/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) release/moc_predefs.h
release/moc_predefs.h: ../../../../app/qt5.13/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o release/moc_predefs.h ../../../../app/qt5.13/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: release/moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) release/moc_widget.cpp
release/moc_widget.cpp: src/widget.h \
		../../../../app/qt5.13/include/QtWidgets/QWidget \
		../../../../app/qt5.13/include/QtWidgets/qwidget.h \
		../../../../app/qt5.13/include/QtWidgets/qtwidgetsglobal.h \
		../../../../app/qt5.13/include/QtGui/qtguiglobal.h \
		../../../../app/qt5.13/include/QtCore/qglobal.h \
		../../../../app/qt5.13/include/QtCore/qconfig-bootstrapped.h \
		../../../../app/qt5.13/include/QtCore/qconfig.h \
		../../../../app/qt5.13/include/QtCore/qtcore-config.h \
		../../../../app/qt5.13/include/QtCore/qsystemdetection.h \
		../../../../app/qt5.13/include/QtCore/qprocessordetection.h \
		../../../../app/qt5.13/include/QtCore/qcompilerdetection.h \
		../../../../app/qt5.13/include/QtCore/qtypeinfo.h \
		../../../../app/qt5.13/include/QtCore/qsysinfo.h \
		../../../../app/qt5.13/include/QtCore/qlogging.h \
		../../../../app/qt5.13/include/QtCore/qflags.h \
		../../../../app/qt5.13/include/QtCore/qatomic.h \
		../../../../app/qt5.13/include/QtCore/qbasicatomic.h \
		../../../../app/qt5.13/include/QtCore/qatomic_bootstrap.h \
		../../../../app/qt5.13/include/QtCore/qgenericatomic.h \
		../../../../app/qt5.13/include/QtCore/qatomic_cxx11.h \
		../../../../app/qt5.13/include/QtCore/qatomic_msvc.h \
		../../../../app/qt5.13/include/QtCore/qglobalstatic.h \
		../../../../app/qt5.13/include/QtCore/qmutex.h \
		../../../../app/qt5.13/include/QtCore/qnumeric.h \
		../../../../app/qt5.13/include/QtCore/qversiontagging.h \
		../../../../app/qt5.13/include/QtGui/qtgui-config.h \
		../../../../app/qt5.13/include/QtWidgets/qtwidgets-config.h \
		../../../../app/qt5.13/include/QtGui/qwindowdefs.h \
		../../../../app/qt5.13/include/QtCore/qobjectdefs.h \
		../../../../app/qt5.13/include/QtCore/qnamespace.h \
		../../../../app/qt5.13/include/QtCore/qobjectdefs_impl.h \
		../../../../app/qt5.13/include/QtGui/qwindowdefs_win.h \
		../../../../app/qt5.13/include/QtCore/qobject.h \
		../../../../app/qt5.13/include/QtCore/qstring.h \
		../../../../app/qt5.13/include/QtCore/qchar.h \
		../../../../app/qt5.13/include/QtCore/qbytearray.h \
		../../../../app/qt5.13/include/QtCore/qrefcount.h \
		../../../../app/qt5.13/include/QtCore/qarraydata.h \
		../../../../app/qt5.13/include/QtCore/qstringliteral.h \
		../../../../app/qt5.13/include/QtCore/qstringalgorithms.h \
		../../../../app/qt5.13/include/QtCore/qstringview.h \
		../../../../app/qt5.13/include/QtCore/qstringbuilder.h \
		../../../../app/qt5.13/include/QtCore/qlist.h \
		../../../../app/qt5.13/include/QtCore/qalgorithms.h \
		../../../../app/qt5.13/include/QtCore/qiterator.h \
		../../../../app/qt5.13/include/QtCore/qhashfunctions.h \
		../../../../app/qt5.13/include/QtCore/qpair.h \
		../../../../app/qt5.13/include/QtCore/qvector.h \
		../../../../app/qt5.13/include/QtCore/qpoint.h \
		../../../../app/qt5.13/include/QtCore/qbytearraylist.h \
		../../../../app/qt5.13/include/QtCore/qstringlist.h \
		../../../../app/qt5.13/include/QtCore/qregexp.h \
		../../../../app/qt5.13/include/QtCore/qstringmatcher.h \
		../../../../app/qt5.13/include/QtCore/qcoreevent.h \
		../../../../app/qt5.13/include/QtCore/qscopedpointer.h \
		../../../../app/qt5.13/include/QtCore/qmetatype.h \
		../../../../app/qt5.13/include/QtCore/qvarlengtharray.h \
		../../../../app/qt5.13/include/QtCore/qcontainerfwd.h \
		../../../../app/qt5.13/include/QtCore/qobject_impl.h \
		../../../../app/qt5.13/include/QtCore/qmargins.h \
		../../../../app/qt5.13/include/QtGui/qpaintdevice.h \
		../../../../app/qt5.13/include/QtCore/qrect.h \
		../../../../app/qt5.13/include/QtCore/qsize.h \
		../../../../app/qt5.13/include/QtGui/qpalette.h \
		../../../../app/qt5.13/include/QtGui/qcolor.h \
		../../../../app/qt5.13/include/QtGui/qrgb.h \
		../../../../app/qt5.13/include/QtGui/qrgba64.h \
		../../../../app/qt5.13/include/QtGui/qbrush.h \
		../../../../app/qt5.13/include/QtGui/qmatrix.h \
		../../../../app/qt5.13/include/QtGui/qpolygon.h \
		../../../../app/qt5.13/include/QtGui/qregion.h \
		../../../../app/qt5.13/include/QtCore/qdatastream.h \
		../../../../app/qt5.13/include/QtCore/qiodevice.h \
		../../../../app/qt5.13/include/QtCore/qline.h \
		../../../../app/qt5.13/include/QtGui/qtransform.h \
		../../../../app/qt5.13/include/QtGui/qpainterpath.h \
		../../../../app/qt5.13/include/QtGui/qimage.h \
		../../../../app/qt5.13/include/QtGui/qpixelformat.h \
		../../../../app/qt5.13/include/QtGui/qpixmap.h \
		../../../../app/qt5.13/include/QtCore/qsharedpointer.h \
		../../../../app/qt5.13/include/QtCore/qshareddata.h \
		../../../../app/qt5.13/include/QtCore/qhash.h \
		../../../../app/qt5.13/include/QtCore/qsharedpointer_impl.h \
		../../../../app/qt5.13/include/QtGui/qfont.h \
		../../../../app/qt5.13/include/QtGui/qfontmetrics.h \
		../../../../app/qt5.13/include/QtGui/qfontinfo.h \
		../../../../app/qt5.13/include/QtWidgets/qsizepolicy.h \
		../../../../app/qt5.13/include/QtGui/qcursor.h \
		../../../../app/qt5.13/include/QtGui/qkeysequence.h \
		../../../../app/qt5.13/include/QtGui/qevent.h \
		../../../../app/qt5.13/include/QtCore/qvariant.h \
		../../../../app/qt5.13/include/QtCore/qmap.h \
		../../../../app/qt5.13/include/QtCore/qdebug.h \
		../../../../app/qt5.13/include/QtCore/qtextstream.h \
		../../../../app/qt5.13/include/QtCore/qlocale.h \
		../../../../app/qt5.13/include/QtCore/qset.h \
		../../../../app/qt5.13/include/QtCore/qcontiguouscache.h \
		../../../../app/qt5.13/include/QtCore/qurl.h \
		../../../../app/qt5.13/include/QtCore/qurlquery.h \
		../../../../app/qt5.13/include/QtCore/qfile.h \
		../../../../app/qt5.13/include/QtCore/qfiledevice.h \
		../../../../app/qt5.13/include/QtGui/qvector2d.h \
		../../../../app/qt5.13/include/QtGui/qtouchdevice.h \
		../../../../app/qt5.13/include/QtWidgets/QMessageBox \
		../../../../app/qt5.13/include/QtWidgets/qmessagebox.h \
		../../../../app/qt5.13/include/QtWidgets/qdialog.h \
		../../../../app/qt5.13/include/QtCore/QDebug \
		../../../../app/qt5.13/include/QtWidgets/QLabel \
		../../../../app/qt5.13/include/QtWidgets/qlabel.h \
		../../../../app/qt5.13/include/QtWidgets/qframe.h \
		../../../../app/qt5.13/include/QtCore/QTimer \
		../../../../app/qt5.13/include/QtCore/qtimer.h \
		../../../../app/qt5.13/include/QtCore/qbasictimer.h \
		../../../../app/qt5.13/include/QtGui/QTextCursor \
		../../../../app/qt5.13/include/QtGui/qtextcursor.h \
		../../../../app/qt5.13/include/QtGui/qtextformat.h \
		../../../../app/qt5.13/include/QtGui/qpen.h \
		../../../../app/qt5.13/include/QtGui/qtextoption.h \
		../../../../app/qt5.13/include/QtCore/QStringList \
		../../../../app/qt5.13/include/QtSerialPort/QSerialPort \
		../../../../app/qt5.13/include/QtSerialPort/qserialport.h \
		../../../../app/qt5.13/include/QtSerialPort/qserialportglobal.h \
		../../../../app/qt5.13/include/QtSerialPort/QSerialPortInfo \
		../../../../app/qt5.13/include/QtSerialPort/qserialportinfo.h \
		release/moc_predefs.h \
		../../../../app/qt5.13/bin/moc
	/data/app/qt5.13/bin/moc $(DEFINES) --include /data/work/workspace/etool/ESerialPort/release/moc_predefs.h -I/data/app/qt5.13/mkspecs/linux-g++ -I/data/work/workspace/etool/ESerialPort -I/data/app/qt5.13/include -I/data/app/qt5.13/include/QtWidgets -I/data/app/qt5.13/include/QtGui -I/data/app/qt5.13/include/QtSerialPort -I/data/app/qt5.13/include/QtCore -I/usr/include/c++/9.2.0 -I/usr/include/c++/9.2.0/x86_64-pc-linux-gnu -I/usr/include/c++/9.2.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed -I/usr/include src/widget.h -o release/moc_widget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_widget.h
ui/ui_widget.h: src/widget.ui \
		../../../../app/qt5.13/bin/uic
	/data/app/qt5.13/bin/uic src/widget.ui -o ui/ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

release/main.o: src/main.cpp src/widget.h \
		../../../../app/qt5.13/include/QtWidgets/QWidget \
		../../../../app/qt5.13/include/QtWidgets/qwidget.h \
		../../../../app/qt5.13/include/QtWidgets/qtwidgetsglobal.h \
		../../../../app/qt5.13/include/QtGui/qtguiglobal.h \
		../../../../app/qt5.13/include/QtCore/qglobal.h \
		../../../../app/qt5.13/include/QtCore/qconfig-bootstrapped.h \
		../../../../app/qt5.13/include/QtCore/qconfig.h \
		../../../../app/qt5.13/include/QtCore/qtcore-config.h \
		../../../../app/qt5.13/include/QtCore/qsystemdetection.h \
		../../../../app/qt5.13/include/QtCore/qprocessordetection.h \
		../../../../app/qt5.13/include/QtCore/qcompilerdetection.h \
		../../../../app/qt5.13/include/QtCore/qtypeinfo.h \
		../../../../app/qt5.13/include/QtCore/qsysinfo.h \
		../../../../app/qt5.13/include/QtCore/qlogging.h \
		../../../../app/qt5.13/include/QtCore/qflags.h \
		../../../../app/qt5.13/include/QtCore/qatomic.h \
		../../../../app/qt5.13/include/QtCore/qbasicatomic.h \
		../../../../app/qt5.13/include/QtCore/qatomic_bootstrap.h \
		../../../../app/qt5.13/include/QtCore/qgenericatomic.h \
		../../../../app/qt5.13/include/QtCore/qatomic_cxx11.h \
		../../../../app/qt5.13/include/QtCore/qatomic_msvc.h \
		../../../../app/qt5.13/include/QtCore/qglobalstatic.h \
		../../../../app/qt5.13/include/QtCore/qmutex.h \
		../../../../app/qt5.13/include/QtCore/qnumeric.h \
		../../../../app/qt5.13/include/QtCore/qversiontagging.h \
		../../../../app/qt5.13/include/QtGui/qtgui-config.h \
		../../../../app/qt5.13/include/QtWidgets/qtwidgets-config.h \
		../../../../app/qt5.13/include/QtGui/qwindowdefs.h \
		../../../../app/qt5.13/include/QtCore/qobjectdefs.h \
		../../../../app/qt5.13/include/QtCore/qnamespace.h \
		../../../../app/qt5.13/include/QtCore/qobjectdefs_impl.h \
		../../../../app/qt5.13/include/QtGui/qwindowdefs_win.h \
		../../../../app/qt5.13/include/QtCore/qobject.h \
		../../../../app/qt5.13/include/QtCore/qstring.h \
		../../../../app/qt5.13/include/QtCore/qchar.h \
		../../../../app/qt5.13/include/QtCore/qbytearray.h \
		../../../../app/qt5.13/include/QtCore/qrefcount.h \
		../../../../app/qt5.13/include/QtCore/qarraydata.h \
		../../../../app/qt5.13/include/QtCore/qstringliteral.h \
		../../../../app/qt5.13/include/QtCore/qstringalgorithms.h \
		../../../../app/qt5.13/include/QtCore/qstringview.h \
		../../../../app/qt5.13/include/QtCore/qstringbuilder.h \
		../../../../app/qt5.13/include/QtCore/qlist.h \
		../../../../app/qt5.13/include/QtCore/qalgorithms.h \
		../../../../app/qt5.13/include/QtCore/qiterator.h \
		../../../../app/qt5.13/include/QtCore/qhashfunctions.h \
		../../../../app/qt5.13/include/QtCore/qpair.h \
		../../../../app/qt5.13/include/QtCore/qvector.h \
		../../../../app/qt5.13/include/QtCore/qpoint.h \
		../../../../app/qt5.13/include/QtCore/qbytearraylist.h \
		../../../../app/qt5.13/include/QtCore/qstringlist.h \
		../../../../app/qt5.13/include/QtCore/qregexp.h \
		../../../../app/qt5.13/include/QtCore/qstringmatcher.h \
		../../../../app/qt5.13/include/QtCore/qcoreevent.h \
		../../../../app/qt5.13/include/QtCore/qscopedpointer.h \
		../../../../app/qt5.13/include/QtCore/qmetatype.h \
		../../../../app/qt5.13/include/QtCore/qvarlengtharray.h \
		../../../../app/qt5.13/include/QtCore/qcontainerfwd.h \
		../../../../app/qt5.13/include/QtCore/qobject_impl.h \
		../../../../app/qt5.13/include/QtCore/qmargins.h \
		../../../../app/qt5.13/include/QtGui/qpaintdevice.h \
		../../../../app/qt5.13/include/QtCore/qrect.h \
		../../../../app/qt5.13/include/QtCore/qsize.h \
		../../../../app/qt5.13/include/QtGui/qpalette.h \
		../../../../app/qt5.13/include/QtGui/qcolor.h \
		../../../../app/qt5.13/include/QtGui/qrgb.h \
		../../../../app/qt5.13/include/QtGui/qrgba64.h \
		../../../../app/qt5.13/include/QtGui/qbrush.h \
		../../../../app/qt5.13/include/QtGui/qmatrix.h \
		../../../../app/qt5.13/include/QtGui/qpolygon.h \
		../../../../app/qt5.13/include/QtGui/qregion.h \
		../../../../app/qt5.13/include/QtCore/qdatastream.h \
		../../../../app/qt5.13/include/QtCore/qiodevice.h \
		../../../../app/qt5.13/include/QtCore/qline.h \
		../../../../app/qt5.13/include/QtGui/qtransform.h \
		../../../../app/qt5.13/include/QtGui/qpainterpath.h \
		../../../../app/qt5.13/include/QtGui/qimage.h \
		../../../../app/qt5.13/include/QtGui/qpixelformat.h \
		../../../../app/qt5.13/include/QtGui/qpixmap.h \
		../../../../app/qt5.13/include/QtCore/qsharedpointer.h \
		../../../../app/qt5.13/include/QtCore/qshareddata.h \
		../../../../app/qt5.13/include/QtCore/qhash.h \
		../../../../app/qt5.13/include/QtCore/qsharedpointer_impl.h \
		../../../../app/qt5.13/include/QtGui/qfont.h \
		../../../../app/qt5.13/include/QtGui/qfontmetrics.h \
		../../../../app/qt5.13/include/QtGui/qfontinfo.h \
		../../../../app/qt5.13/include/QtWidgets/qsizepolicy.h \
		../../../../app/qt5.13/include/QtGui/qcursor.h \
		../../../../app/qt5.13/include/QtGui/qkeysequence.h \
		../../../../app/qt5.13/include/QtGui/qevent.h \
		../../../../app/qt5.13/include/QtCore/qvariant.h \
		../../../../app/qt5.13/include/QtCore/qmap.h \
		../../../../app/qt5.13/include/QtCore/qdebug.h \
		../../../../app/qt5.13/include/QtCore/qtextstream.h \
		../../../../app/qt5.13/include/QtCore/qlocale.h \
		../../../../app/qt5.13/include/QtCore/qset.h \
		../../../../app/qt5.13/include/QtCore/qcontiguouscache.h \
		../../../../app/qt5.13/include/QtCore/qurl.h \
		../../../../app/qt5.13/include/QtCore/qurlquery.h \
		../../../../app/qt5.13/include/QtCore/qfile.h \
		../../../../app/qt5.13/include/QtCore/qfiledevice.h \
		../../../../app/qt5.13/include/QtGui/qvector2d.h \
		../../../../app/qt5.13/include/QtGui/qtouchdevice.h \
		../../../../app/qt5.13/include/QtWidgets/QMessageBox \
		../../../../app/qt5.13/include/QtWidgets/qmessagebox.h \
		../../../../app/qt5.13/include/QtWidgets/qdialog.h \
		../../../../app/qt5.13/include/QtCore/QDebug \
		../../../../app/qt5.13/include/QtWidgets/QLabel \
		../../../../app/qt5.13/include/QtWidgets/qlabel.h \
		../../../../app/qt5.13/include/QtWidgets/qframe.h \
		../../../../app/qt5.13/include/QtCore/QTimer \
		../../../../app/qt5.13/include/QtCore/qtimer.h \
		../../../../app/qt5.13/include/QtCore/qbasictimer.h \
		../../../../app/qt5.13/include/QtGui/QTextCursor \
		../../../../app/qt5.13/include/QtGui/qtextcursor.h \
		../../../../app/qt5.13/include/QtGui/qtextformat.h \
		../../../../app/qt5.13/include/QtGui/qpen.h \
		../../../../app/qt5.13/include/QtGui/qtextoption.h \
		../../../../app/qt5.13/include/QtCore/QStringList \
		../../../../app/qt5.13/include/QtSerialPort/QSerialPort \
		../../../../app/qt5.13/include/QtSerialPort/qserialport.h \
		../../../../app/qt5.13/include/QtSerialPort/qserialportglobal.h \
		../../../../app/qt5.13/include/QtSerialPort/QSerialPortInfo \
		../../../../app/qt5.13/include/QtSerialPort/qserialportinfo.h \
		../../../../app/qt5.13/include/QtWidgets/QApplication \
		../../../../app/qt5.13/include/QtWidgets/qapplication.h \
		../../../../app/qt5.13/include/QtCore/qcoreapplication.h \
		../../../../app/qt5.13/include/QtCore/qeventloop.h \
		../../../../app/qt5.13/include/QtWidgets/qdesktopwidget.h \
		../../../../app/qt5.13/include/QtGui/qguiapplication.h \
		../../../../app/qt5.13/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/main.o src/main.cpp

release/widget.o: src/widget.cpp src/widget.h \
		../../../../app/qt5.13/include/QtWidgets/QWidget \
		../../../../app/qt5.13/include/QtWidgets/qwidget.h \
		../../../../app/qt5.13/include/QtWidgets/qtwidgetsglobal.h \
		../../../../app/qt5.13/include/QtGui/qtguiglobal.h \
		../../../../app/qt5.13/include/QtCore/qglobal.h \
		../../../../app/qt5.13/include/QtCore/qconfig-bootstrapped.h \
		../../../../app/qt5.13/include/QtCore/qconfig.h \
		../../../../app/qt5.13/include/QtCore/qtcore-config.h \
		../../../../app/qt5.13/include/QtCore/qsystemdetection.h \
		../../../../app/qt5.13/include/QtCore/qprocessordetection.h \
		../../../../app/qt5.13/include/QtCore/qcompilerdetection.h \
		../../../../app/qt5.13/include/QtCore/qtypeinfo.h \
		../../../../app/qt5.13/include/QtCore/qsysinfo.h \
		../../../../app/qt5.13/include/QtCore/qlogging.h \
		../../../../app/qt5.13/include/QtCore/qflags.h \
		../../../../app/qt5.13/include/QtCore/qatomic.h \
		../../../../app/qt5.13/include/QtCore/qbasicatomic.h \
		../../../../app/qt5.13/include/QtCore/qatomic_bootstrap.h \
		../../../../app/qt5.13/include/QtCore/qgenericatomic.h \
		../../../../app/qt5.13/include/QtCore/qatomic_cxx11.h \
		../../../../app/qt5.13/include/QtCore/qatomic_msvc.h \
		../../../../app/qt5.13/include/QtCore/qglobalstatic.h \
		../../../../app/qt5.13/include/QtCore/qmutex.h \
		../../../../app/qt5.13/include/QtCore/qnumeric.h \
		../../../../app/qt5.13/include/QtCore/qversiontagging.h \
		../../../../app/qt5.13/include/QtGui/qtgui-config.h \
		../../../../app/qt5.13/include/QtWidgets/qtwidgets-config.h \
		../../../../app/qt5.13/include/QtGui/qwindowdefs.h \
		../../../../app/qt5.13/include/QtCore/qobjectdefs.h \
		../../../../app/qt5.13/include/QtCore/qnamespace.h \
		../../../../app/qt5.13/include/QtCore/qobjectdefs_impl.h \
		../../../../app/qt5.13/include/QtGui/qwindowdefs_win.h \
		../../../../app/qt5.13/include/QtCore/qobject.h \
		../../../../app/qt5.13/include/QtCore/qstring.h \
		../../../../app/qt5.13/include/QtCore/qchar.h \
		../../../../app/qt5.13/include/QtCore/qbytearray.h \
		../../../../app/qt5.13/include/QtCore/qrefcount.h \
		../../../../app/qt5.13/include/QtCore/qarraydata.h \
		../../../../app/qt5.13/include/QtCore/qstringliteral.h \
		../../../../app/qt5.13/include/QtCore/qstringalgorithms.h \
		../../../../app/qt5.13/include/QtCore/qstringview.h \
		../../../../app/qt5.13/include/QtCore/qstringbuilder.h \
		../../../../app/qt5.13/include/QtCore/qlist.h \
		../../../../app/qt5.13/include/QtCore/qalgorithms.h \
		../../../../app/qt5.13/include/QtCore/qiterator.h \
		../../../../app/qt5.13/include/QtCore/qhashfunctions.h \
		../../../../app/qt5.13/include/QtCore/qpair.h \
		../../../../app/qt5.13/include/QtCore/qvector.h \
		../../../../app/qt5.13/include/QtCore/qpoint.h \
		../../../../app/qt5.13/include/QtCore/qbytearraylist.h \
		../../../../app/qt5.13/include/QtCore/qstringlist.h \
		../../../../app/qt5.13/include/QtCore/qregexp.h \
		../../../../app/qt5.13/include/QtCore/qstringmatcher.h \
		../../../../app/qt5.13/include/QtCore/qcoreevent.h \
		../../../../app/qt5.13/include/QtCore/qscopedpointer.h \
		../../../../app/qt5.13/include/QtCore/qmetatype.h \
		../../../../app/qt5.13/include/QtCore/qvarlengtharray.h \
		../../../../app/qt5.13/include/QtCore/qcontainerfwd.h \
		../../../../app/qt5.13/include/QtCore/qobject_impl.h \
		../../../../app/qt5.13/include/QtCore/qmargins.h \
		../../../../app/qt5.13/include/QtGui/qpaintdevice.h \
		../../../../app/qt5.13/include/QtCore/qrect.h \
		../../../../app/qt5.13/include/QtCore/qsize.h \
		../../../../app/qt5.13/include/QtGui/qpalette.h \
		../../../../app/qt5.13/include/QtGui/qcolor.h \
		../../../../app/qt5.13/include/QtGui/qrgb.h \
		../../../../app/qt5.13/include/QtGui/qrgba64.h \
		../../../../app/qt5.13/include/QtGui/qbrush.h \
		../../../../app/qt5.13/include/QtGui/qmatrix.h \
		../../../../app/qt5.13/include/QtGui/qpolygon.h \
		../../../../app/qt5.13/include/QtGui/qregion.h \
		../../../../app/qt5.13/include/QtCore/qdatastream.h \
		../../../../app/qt5.13/include/QtCore/qiodevice.h \
		../../../../app/qt5.13/include/QtCore/qline.h \
		../../../../app/qt5.13/include/QtGui/qtransform.h \
		../../../../app/qt5.13/include/QtGui/qpainterpath.h \
		../../../../app/qt5.13/include/QtGui/qimage.h \
		../../../../app/qt5.13/include/QtGui/qpixelformat.h \
		../../../../app/qt5.13/include/QtGui/qpixmap.h \
		../../../../app/qt5.13/include/QtCore/qsharedpointer.h \
		../../../../app/qt5.13/include/QtCore/qshareddata.h \
		../../../../app/qt5.13/include/QtCore/qhash.h \
		../../../../app/qt5.13/include/QtCore/qsharedpointer_impl.h \
		../../../../app/qt5.13/include/QtGui/qfont.h \
		../../../../app/qt5.13/include/QtGui/qfontmetrics.h \
		../../../../app/qt5.13/include/QtGui/qfontinfo.h \
		../../../../app/qt5.13/include/QtWidgets/qsizepolicy.h \
		../../../../app/qt5.13/include/QtGui/qcursor.h \
		../../../../app/qt5.13/include/QtGui/qkeysequence.h \
		../../../../app/qt5.13/include/QtGui/qevent.h \
		../../../../app/qt5.13/include/QtCore/qvariant.h \
		../../../../app/qt5.13/include/QtCore/qmap.h \
		../../../../app/qt5.13/include/QtCore/qdebug.h \
		../../../../app/qt5.13/include/QtCore/qtextstream.h \
		../../../../app/qt5.13/include/QtCore/qlocale.h \
		../../../../app/qt5.13/include/QtCore/qset.h \
		../../../../app/qt5.13/include/QtCore/qcontiguouscache.h \
		../../../../app/qt5.13/include/QtCore/qurl.h \
		../../../../app/qt5.13/include/QtCore/qurlquery.h \
		../../../../app/qt5.13/include/QtCore/qfile.h \
		../../../../app/qt5.13/include/QtCore/qfiledevice.h \
		../../../../app/qt5.13/include/QtGui/qvector2d.h \
		../../../../app/qt5.13/include/QtGui/qtouchdevice.h \
		../../../../app/qt5.13/include/QtWidgets/QMessageBox \
		../../../../app/qt5.13/include/QtWidgets/qmessagebox.h \
		../../../../app/qt5.13/include/QtWidgets/qdialog.h \
		../../../../app/qt5.13/include/QtCore/QDebug \
		../../../../app/qt5.13/include/QtWidgets/QLabel \
		../../../../app/qt5.13/include/QtWidgets/qlabel.h \
		../../../../app/qt5.13/include/QtWidgets/qframe.h \
		../../../../app/qt5.13/include/QtCore/QTimer \
		../../../../app/qt5.13/include/QtCore/qtimer.h \
		../../../../app/qt5.13/include/QtCore/qbasictimer.h \
		../../../../app/qt5.13/include/QtGui/QTextCursor \
		../../../../app/qt5.13/include/QtGui/qtextcursor.h \
		../../../../app/qt5.13/include/QtGui/qtextformat.h \
		../../../../app/qt5.13/include/QtGui/qpen.h \
		../../../../app/qt5.13/include/QtGui/qtextoption.h \
		../../../../app/qt5.13/include/QtCore/QStringList \
		../../../../app/qt5.13/include/QtSerialPort/QSerialPort \
		../../../../app/qt5.13/include/QtSerialPort/qserialport.h \
		../../../../app/qt5.13/include/QtSerialPort/qserialportglobal.h \
		../../../../app/qt5.13/include/QtSerialPort/QSerialPortInfo \
		../../../../app/qt5.13/include/QtSerialPort/qserialportinfo.h \
		ui/ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/widget.o src/widget.cpp

release/moc_widget.o: release/moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/moc_widget.o release/moc_widget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

