#############################################################################
# Makefile for building: release/ESerialPort
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  ESerialPort.pro
# Template: app
# Command: /data/app/Qt5.6.3/5.6.3/gcc_64/bin/qmake -o Makefile ESerialPort.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -std=gnu11 -Wno-deprecated-copy -Wno-unused-parameter -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -Wno-deprecated-copy -Wno-unused-parameter -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../app/Qt5.6.3/5.6.3/gcc_64/include -I../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets -I../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui -I../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort -I../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore -Irelease -Iui -I../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++
QMAKE         = /data/app/Qt5.6.3/5.6.3/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ESerialPort1.0.0
DISTDIR = /data/work/workspace/etool/ESerialPort/release/ESerialPort1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/data/app/Qt5.6.3/5.6.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L/data/app/Qt5.6.3/5.6.3/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5SerialPort -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = release/

####### Files

SOURCES       = src/main.cpp \
		src/widget.cpp release/moc_widget.cpp
OBJECTS       = release/main.o \
		release/widget.o \
		release/moc_widget.o
DIST          = ../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_pre.prf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/unix.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/linux.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/sanitize.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-base.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/qconfig.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_post.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_post.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/warn_on.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resources.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/moc.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/uic.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/file_copies.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exceptions.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/yacc.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/lex.prf \
		ESerialPort.pro src/widget.h src/main.cpp \
		src/widget.cpp
QMAKE_TARGET  = ESerialPort
DESTDIR       = release/
TARGET        = release/ESerialPort


first: all
####### Build rules

$(TARGET): ui/ui_widget.h $(OBJECTS)  
	@test -d release/ || mkdir -p release/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ESerialPort.pro ../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++/qmake.conf ../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_pre.prf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/unix.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/linux.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/sanitize.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-base.conf \
		/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/qconfig.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_config.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_post.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_pre.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_post.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/warn_on.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resources.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/moc.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/uic.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/file_copies.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exceptions.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/yacc.prf \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/lex.prf \
		ESerialPort.pro \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Widgets.prl \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Gui.prl \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/lib/libQt5SerialPort.prl \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ESerialPort.pro
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_pre.prf:
/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/unix.conf:
/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/linux.conf:
/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/sanitize.conf:
/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base.conf:
/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-base.conf:
/home/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/common/g++-unix.conf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/qconfig.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_functions.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt_config.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/spec_post.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_pre.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resolve_config.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/default_post.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/warn_on.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/qt.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/resources.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/moc.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/opengl.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/uic.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/unix/thread.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/file_copies.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/testcase_targets.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/exceptions.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/yacc.prf:
../../../../app/Qt5.6.3/5.6.3/gcc_64/mkspecs/features/lex.prf:
ESerialPort.pro:
../../../../app/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Widgets.prl:
../../../../app/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Gui.prl:
../../../../app/Qt5.6.3/5.6.3/gcc_64/lib/libQt5SerialPort.prl:
../../../../app/Qt5.6.3/5.6.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ESerialPort.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/widget.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: release/moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) release/moc_widget.cpp
release/moc_widget.cpp: ../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/QWidget \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qwidget.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qglobal.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qconfig.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qfeatures.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtypetraits.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qisenum.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlogging.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qflags.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmutex.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qnumeric.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qversiontagging.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qnamespace.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobject.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstring.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qchar.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbytearray.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qrefcount.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qarraydata.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlist.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qiterator.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qpair.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringlist.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qregexp.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcoreevent.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmetatype.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobject_impl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmargins.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qrect.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsize.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qpoint.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpalette.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qcolor.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qrgb.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qrgba64.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qbrush.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvector.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qmatrix.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpolygon.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qregion.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qdatastream.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qiodevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qline.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtransform.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpainterpath.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qimage.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpixelformat.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpixmap.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qshareddata.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qhash.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qfont.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qfontinfo.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qcursor.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qkeysequence.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qevent.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvariant.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmap.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qdebug.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtextstream.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlocale.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qset.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qurl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qurlquery.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qfile.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qfiledevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qvector2d.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/QMessageBox \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qdialog.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QDebug \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/QLabel \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qlabel.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qframe.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QTimer \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtimer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbasictimer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/QTextCursor \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtextcursor.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtextformat.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpen.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtextoption.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QStringList \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/QSerialPort \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/qserialport.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/qserialportglobal.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/QSerialPortInfo \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/qserialportinfo.h \
		src/widget.h
	/data/app/Qt5.6.3/5.6.3/gcc_64/bin/moc $(DEFINES) -I/data/app/Qt5.6.3/5.6.3/gcc_64/mkspecs/linux-g++ -I/data/work/workspace/etool/ESerialPort -I/data/app/Qt5.6.3/5.6.3/gcc_64/include -I/data/app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets -I/data/app/Qt5.6.3/5.6.3/gcc_64/include/QtGui -I/data/app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort -I/data/app/Qt5.6.3/5.6.3/gcc_64/include/QtCore src/widget.h -o release/moc_widget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui/ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui/ui_widget.h
ui/ui_widget.h: src/widget.ui
	/data/app/Qt5.6.3/5.6.3/gcc_64/bin/uic src/widget.ui -o ui/ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

release/main.o: src/main.cpp src/widget.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/QWidget \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qwidget.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qglobal.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qconfig.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qfeatures.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtypetraits.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qisenum.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlogging.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qflags.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmutex.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qnumeric.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qversiontagging.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qnamespace.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobject.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstring.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qchar.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbytearray.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qrefcount.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qarraydata.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlist.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qiterator.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qpair.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringlist.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qregexp.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcoreevent.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmetatype.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobject_impl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmargins.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qrect.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsize.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qpoint.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpalette.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qcolor.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qrgb.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qrgba64.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qbrush.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvector.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qmatrix.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpolygon.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qregion.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qdatastream.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qiodevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qline.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtransform.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpainterpath.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qimage.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpixelformat.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpixmap.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qshareddata.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qhash.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qfont.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qfontinfo.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qcursor.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qkeysequence.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qevent.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvariant.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmap.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qdebug.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtextstream.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlocale.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qset.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qurl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qurlquery.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qfile.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qfiledevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qvector2d.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/QMessageBox \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qdialog.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QDebug \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/QLabel \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qlabel.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qframe.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QTimer \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtimer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbasictimer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/QTextCursor \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtextcursor.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtextformat.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpen.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtextoption.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QStringList \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/QSerialPort \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/qserialport.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/qserialportglobal.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/QSerialPortInfo \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/qserialportinfo.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/QApplication \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qapplication.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qeventloop.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qguiapplication.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/main.o src/main.cpp

release/widget.o: src/widget.cpp src/widget.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/QWidget \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qwidget.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qglobal.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qconfig.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qfeatures.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtypetraits.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qisenum.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsysinfo.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlogging.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qflags.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmutex.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qnumeric.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qversiontagging.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qnamespace.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobject.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstring.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qchar.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbytearray.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qrefcount.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qarraydata.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlist.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qalgorithms.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qiterator.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qpair.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringlist.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qregexp.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcoreevent.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmetatype.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qobject_impl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmargins.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qrect.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsize.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qpoint.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpalette.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qcolor.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qrgb.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qrgba64.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qbrush.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvector.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qmatrix.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpolygon.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qregion.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qdatastream.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qiodevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qline.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtransform.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpainterpath.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qimage.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpixelformat.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpixmap.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qshareddata.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qhash.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qfont.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qfontinfo.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qcursor.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qkeysequence.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qevent.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qvariant.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qmap.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qdebug.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtextstream.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qlocale.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qset.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qurl.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qurlquery.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qfile.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qfiledevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qvector2d.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/QMessageBox \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qdialog.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QDebug \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/QLabel \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qlabel.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtWidgets/qframe.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QTimer \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qtimer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/qbasictimer.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/QTextCursor \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtextcursor.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtextformat.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qpen.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtGui/qtextoption.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtCore/QStringList \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/QSerialPort \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/qserialport.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/qserialportglobal.h \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/QSerialPortInfo \
		../../../../app/Qt5.6.3/5.6.3/gcc_64/include/QtSerialPort/qserialportinfo.h \
		ui/ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/widget.o src/widget.cpp

release/moc_widget.o: release/moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/moc_widget.o release/moc_widget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

